### ISSUE TITLE
Filename not using what's in the RSS Config

### ISSUE THREAD

**Issue by pjlamb12** [notiz-dev/scully-plugins#18]
I have the filename set to blog-feed.{xml,json,atom} but it's being output as feed.{xml,json,atom}

**Comment by pjlamb12** [comment]
I think this is actually because with the change, we didn't think about how the plugin would load the rss.config.json file. I bet it's not being loaded.

**Comment by pjlamb12** [comment]
Scratch that, the config file is being loaded, I just thought that the feedLinks object also changed the name of the output file, which isn't what happens.

**Comment by marcjulian** [comment]
Is there an option in feed to change the output filename?

**Comment by marcjulian** [comment]
We are setting the filename `writeFileSync(join(config.outDir || '', 'feed.xml'), feed.rss2());` here we could change it in the config.

**Comment by pjlamb12** [comment]
I will look in Feed and see if it can be changed. I think it's nice to have that control, but don't have strong feelings either way.

**Comment by marcjulian** [comment]
I think we can just change it instead of `feed.xml` we could pulled it in from the config.
